In [1]:
from utils import environment as Env
import operator
import collections
import numpy as np
import scipy.io as sio
def gen_loc_map(loc, mmap):
    loc4maps = []
    loc_map = np.zeros((11, 11))
    xrnge = range(loc[0] - 5, loc[0] + 6); xrnge.reverse()
    yrnge = range(loc[1] - 5, loc[1] + 6); yrnge.reverse()
    for idy, y in enumerate(yrnge):
        for idx, x in enumerate(xrnge):
            if (x, y) in mmap:
                loc_map[idy][idx] = 1
    for i in xrange(4):
        if i == 0:
            loc4maps.append(loc_map)
        else:
            loc_map = np.rot90(loc_map)
            loc4maps.append(loc_map)
    
    return np.stack(loc4maps, axis=0)



In [6]:
from gensmap import gensmap
import cv2
import numpy as np
testhouse = gensmap(env='5cf0e1e9493994e483e985c436b9d3bc', sz=33)
# localsmaps = testhouse.GenSmap()

In [7]:
def chksmap(localsmap, cats):
    
    for j in range(localsmap.shape[-1]):
        viewbycat = np.zeros((localsmap.shape[0], localsmap.shape[1]),
                             dtype=np.uint8)
        viewbycat[localsmap[..., j] == 1] = 255
        if np.sum(viewbycat) != 0:
            # print (viewbycat)
            print (j, cats[j])
            cv2.imshow("debug", np.transpose(viewbycat))
            key = cv2.waitKey(0)
            if key == ord('q'):
                cv2.destroyAllWindows()
# Check the local semantic maps
import pickle
HOUSEDIR = '/media/z/Data/Object_Searching/code/Environment/houses'
houseid = '5cf0e1e9493994e483e985c436b9d3bc'

lsmaps = pickle.load(open('%s/%s/planner_data/localsmaps_31.pkl' % (HOUSEDIR, houseid), 'rb'))
cat = testhouse.cat
for i, cati in enumerate(cat):
    print ('class label index is %d, category name is %s.' % (i, cati))

class label index is 0, category name is toilet.
class label index is 1, category name is heater.
class label index is 2, category name is tv_stand.
class label index is 3, category name is mirror.
class label index is 4, category name is ottoman.
class label index is 5, category name is dressing_table.
class label index is 6, category name is toy.
class label index is 7, category name is clock.
class label index is 8, category name is wardrobe_cabinet.
class label index is 9, category name is music.
class label index is 10, category name is table_and_chair.
class label index is 11, category name is vase.
class label index is 12, category name is sink.
class label index is 13, category name is desk.
class label index is 14, category name is picture_frame.
class label index is 15, category name is bathroom_stuff.
class label index is 16, category name is table.
class label index is 17, category name is television.
class label index is 18, category name is shoes_cabinet.
class label inde

In [4]:
chksmap(lsmaps[(12, 23)], cat)
# chksmap(lsmaps[(12, 29)], cat)
### Check passedq



(2, u'tv_stand')
(9, u'music')
(16, u'table')
(17, u'television')
(20, u'sofa')


IndexError: list index out of range

### CHECK navi_env functions

In [1]:
from src.navi_env import Environment
from src.utils import Foo
houseid = '5cf0e1e9493994e483e985c436b9d3bc'
navi = Foo(batch_size=4, map_orig_sizes=[11,21,31], 
           map_scales=[11, 21, 31], map_crop_sizes=[11]*3, map_channels=26)
env = Environment(houseid, navi)

In [2]:
import numpy as np
rng = np.random.RandomState(1008)
env.reset(rng, multi_target=['television', 'stand', 'desk', 'toilet'])

[[-5, 12, 1], [-5, 31, 2], [-11, 12, 3], [-5, 9, 1]]


[[-5, 12, 1], [-5, 31, 2], [-11, 12, 3], [-5, 9, 1]]

In [5]:
pos = env.startatPos([(9,25,1) for i in range(navi.batch_size)])
# for i in range(10):
#     print env.step([1,2,3,4,5,5,1,2])

In [15]:
env.get_batch_g_ids()

[1400, 1994, 3053, 734, 1590, 2743, 1943, 1320]

In [6]:
a = env.get_state_locsmap(12,29,0,33)
cat.append('other')
chksmap(a, cat)

(4, u'ottoman')
(21, u'bed')
(23, u'stand')
(25, 'other')


In [3]:
a = env.get_batch_dist()

In [11]:
a = env.get_batch_locsmaps(33)

In [12]:
a = env.get_batch_img('rgb')

In [13]:
a = env.success()

In [19]:
a = env.get_common_data()

In [6]:
a = env.get_step_data()

In [6]:
a = env.get_batch_gt_actions()

In [13]:
a = env.get_step_data_names()

In [3]:
a = env.get_batch_onehot_semantic()

In [ ]:
env.gt_loc_aseq[(-12, 39, 0)]

In [21]:
import tensorflow as tf
a = tf.constant([
    [[1, 2, 3, 4], [1,2,3,4]],
    [[5, 6, 7, 8], [5,6,7,8]],
    [[1, 2, 3, 4], [1,2,4,3]]
], dtype=tf.float32)

b = tf.reduce_sum(a, reduction_indices=1)
c = tf.maximum(b, tf.constant(10.))
# c = a / tf.reshape(b, (-1, 1))
with tf.Session() as sess:
    print sess.run(c)
    

[[10. 10. 10. 10.]
 [10. 12. 14. 16.]
 [10. 10. 10. 10.]]
